//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Glyde.ServiceModel.Examples", ConfigurationName="IStringManipulator")]
public interface IStringManipulator
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Glyde.ServiceModel.Examples/IStringManipulator/Add", ReplyAction="http://Glyde.ServiceModel.Examples/IStringManipulator/AddResponse")]
    string Add(string s1, string s2);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Glyde.ServiceModel.Examples/IStringManipulator/Delete", ReplyAction="http://Glyde.ServiceModel.Examples/IStringManipulator/DeleteResponse")]
    string Delete(string s1, string s2);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Glyde.ServiceModel.Examples/IStringManipulator/Replace", ReplyAction="http://Glyde.ServiceModel.Examples/IStringManipulator/ReplaceResponse")]
    string Replace(string s1, string s2, string s3);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStringManipulatorChannel : IStringManipulator, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StringManipulatorClient : System.ServiceModel.ClientBase<IStringManipulator>, IStringManipulator
{
    
    public StringManipulatorClient()
    {
    }
    
    public StringManipulatorClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StringManipulatorClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringManipulatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringManipulatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Add(string s1, string s2)
    {
        return base.Channel.Add(s1, s2);
    }
    
    public string Delete(string s1, string s2)
    {
        return base.Channel.Delete(s1, s2);
    }
    
    public string Replace(string s1, string s2, string s3)
    {
        return base.Channel.Replace(s1, s2, s3);
    }
}
